### ISSUE TITLE
Can't process columns with null values?

### ISSUE THREAD

**Issue by allurefx** [pacman82/arrow-odbc#100]
I'm getting errors with MSSQL columns with no content. On debugging it seems to happen in choose_text_strategy(), this is Ubuntu. Below is the bad sql_type that seems to be triggering the error. Could you please suggest a workaround because I'm not able to use arrow_odbc because of this issue. Thanks!

```
?sql_type
{column_size:None, decimal_digits:0}
data_type: {0:-151}
0: -151
column_size: None
[raw]: core::option::Option<core::num::nonzero::NonZero<usize>>::None
decimal_digits: 0
```

**Comment by pacman82** [comment]
What is the error emitted by `arrow-odbc` and which function returns it?

**Comment by allurefx** [comment]
It happens in OdbcReaderBuilder::new().build(cursor). Below is the error:
```
ColumnFailure {
    name: "Location",
    index: 0,
    source: ZeroSizedColumn {
        sql_type: Other {
            data_type: SqlDataType(
                -151,
            ),
            column_size: None,
            decimal_digits: 0,
        },
    },
}
```

**Comment by pacman82** [comment]
Using the `Display` trait to render the error rather than `Debug` one gets a human readable description. You can look it up in code here: <https://github.com/pacman82/arrow-odbc/blob/55dec538dd7066dc709ceb9feb61e370fded6b1c/src/reader.rs#L205>

This is a variadic type without an upper bound. `arrow-odbc` will process it just fine, but you need to give it an upper bound. You can do so using `with_max_text_size`. See: <https://docs.rs/arrow-odbc/latest/arrow_odbc/struct.OdbcReaderBuilder.html#method.with_max_text_size>

**Comment by pacman82** [comment]
Hello @allurefx ,

does `with_max_text_size` help you? Did the documentation help understanding the issue?

Best, Markus

**Comment by pacman82** [comment]
Closing this issue for now. As far as I can tell `with_max_text_size` should already allow you to mitigate the situation. Please reopen the ticket if this is not true.

Best, Markus

**Comment by allurefx** [comment]
Thanks @pacman82, I finally got the chance to test this and it appears to be working once I specify a max value. I'll post back if I run into this or other issues, thanks again for your prompt responses and support.
