### ISSUE TITLE
application run  crash

### ISSUE THREAD

**Issue by web3creator** [pacman82/arrow-odbc#77]
```
        let cursor = conn
            .execute("SHOW COLUMNS FROM  hello", ())
            .unwrap()
            .expect("");
        // Each batch shall only consist of maximum 10.000 rows.
        let max_batch_size = 10_000;
        // Read result set as arrow batches. Infer Arrow types automatically using the meta
        // information of `cursor`.
        let mut arrow_record_batches = OdbcReader::new(cursor, max_batch_size).unwrap();
```

When "SHOW COLUMNS FROM hello" is executed, if batch_size is set to 10000, the program will crash. If it is set to 10, it will not crash.

**Comment by pacman82** [comment]
From what you describe, it sounds as simple to me, as your machine running out of memory. Is there an error message?

**Comment by web3creator** [comment]
@pacman82  
```
SHOW COLUMNS FROM hello
```
It just gets the schema information of the table. This is very strange. I didn't solve it this afternoon. I will take a look at the double line.

**Comment by web3creator** [comment]
@pacman82  I hope he can support more databases on his own, can I prepare together. What are currently supported?

**Comment by pacman82** [comment]
There should be a backtrace and an error message. Most likely though you run out of memory, because the database you use, most likely does not have sensible upper bounds on the maximum length of the text fields schema information.

Please check the documentation about `max_text_size` about limiting buffer length for individual fields: <https://docs.rs/arrow-odbc/latest/arrow_odbc/struct.BufferAllocationOptions.html#structfield.max_binary_size>

You can change your call to `OdbcReader::new` like this.

```rust
let arrow_record_batches = OdbcReader::with(
        cursor,
        max_batch_size,
        None,
        BufferAllocationOptions {
             // Limit max text size of variadic fields in case the database schema
             // information states something ridicoulisly large.
             max_text_size: Some(4096),
             ..BufferAllocationOptions::default()
        }
)?;
```

**Comment by pacman82** [comment]
`arrow-odbc 3.0.0` is released. It deprecates construction of readers with `new`. The now preferred way to construct it using `OdbcReaderBuilder` enforces a memory limit for the transit buffer. This should make things more explicit.
