### ISSUE TITLE
Performance extremely sensitive to `max_text_size`

### ISSUE THREAD

**Issue by jonashaag** [pacman82/arrow-odbc#87]
It seems like arrow-odbc's performance can be extremely sensitive to the value of `max_text_size`:

```
In [16]: reader = arrow_odbc.read_arrow_batches_from_odbc(..., max_text_size=30)

In [17]: %timeit -n1 -r1 list(reader)
81.1 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [18]: reader = arrow_odbc.read_arrow_batches_from_odbc(..., max_text_size=300)

In [19]: %timeit -n1 -r1 list(reader)
117 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [20]: reader = arrow_odbc.read_arrow_batches_from_odbc(..., max_text_size=3000)

In [21]: %timeit -n1 -r1 list(reader)
6.42 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

When writing library code I have to pick a value large enough to accommodate the longest string the library will ever deal will. In practice this can easily be the 3000 bytes used in the example above, for a 80x slowdown in this case :-(

Version: arrow-odbc-py 2.0.5

**Comment by jonashaag** [comment]
Profile

<img width="920" alt="Screenshot 2023-12-28 at 23 36 15" src="https://github.com/pacman82/arrow-odbc/assets/175722/63dde119-c38b-4046-8e64-48a2da56b00e">

**Comment by jonashaag** [comment]
It looks like utilization of the maximum batch size gets worse with largest numbers of `max_text_size`:

```
In [47]: reader = arrow_odbc.read_arrow_batches_from_odbc(..., max_text_size=30)

In [48]: next(reader).nbytes / 2097152  # <= default max batch bytes
Out[48]: 0.21680784225463867

In [50]: reader = arrow_odbc.read_arrow_batches_from_odbc(..., max_text_size=300)

In [51]: next(reader).nbytes / 2097152
Out[51]: 0.02923440933227539

In [52]: reader = arrow_odbc.read_arrow_batches_from_odbc(..., max_text_size=3000)

In [53]: next(reader).nbytes / 2097152
Out[53]: 0.0027260780334472656
```

If you increase the maximum batch bytes, batch size will grow but utilization stays low.

**Comment by pacman82** [comment]
Your observations are correct and (to me) unsurprising. I updated the comments on `max_text_size` to elaborate further.

If there would have been a good generic way to choose that value I would not forward the decision to the user. At the core of the problem is this. Unbounded columns without upper limits and preallocated buffers which must be able to hold multiple instances of the largest possible values do not mix well.

ODBC 4.0 allows to specify execption behaviour for large values. Yet this is a long way into the future, and even longer until drivers will support it. If ever.

Best fix is almost always to sanatize the database schema. If you do not have 2GiB values in the database why use Varchar(max)?. Second best fix is to use domain knowledge to specify an upper bound. If this is not possible, generic applications could do a first pass with a query do determine the largest values. This should not be done by `arrow-odbc`. First it does not know wether it can reexecute the query without side effects and second the application might be able to come up with a faster query for a first pass.

In terms of `arrow-odbc` I can see myself doing to things:

* Allowing to specify an upper limit per column. Yet this requires even more configuration form the user.
* Using scroll cursors to recover from truncation and bind incrementally larger buffers. Only possible with certain drivers though. I have a working prototype, but it is more work than I am willing to do for free, honestly.
